# Generated by Django 4.2.1 on 2023-05-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_lala',
            field=models.CharField(default='lalala', max_length=100, verbose_name='lala'),
        ),
    ]
